// <auto-generated />
namespace Assesment.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class storedProcedure2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(storedProcedure2));
        
        string IMigrationMetadata.Id
        {
            get { return "202304170726079_storedProcedure2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
